Function fields_for/1 has no local return
Function fields_for/2 only terminates with explicit exception
<<_:40,_:_*8>>
